---
development:
  dialect: "sqlite3"
  database: /Users/manishjha/Desktop/coding/go_apps/test_app/database/test_db_development.sqlite

test:
  dialect: "sqlite3"
  database: /Users/manishjha/Desktop/coding/go_apps/test_app/database/test_db_test.sqlite

production:
  dialect: "sqlite3"
  database: /Users/manishjha/Desktop/coding/go_apps/test_app/database/test_db_production.sqlite
